# -------- STAGE 1 : build --------
FROM python:3.11-slim AS builder

WORKDIR /app

RUN apt update && apt install -y \
    python3-dev \
    gcc \
    build-essential \
    libsasl2-dev \
    libldap2-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# -------- STAGE 2 : runtime --------
FROM python:3.11-slim

WORKDIR /app

RUN apt update && apt install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /install /usr/local
COPY student_age.py .

RUN useradd -m appuser
USER appuser

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD curl -f http://localhost:5000/health || exit 1

CMD ["python", "student_age.py"]
